# -*- coding: utf-8 -*-
"""phishingmail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuS0zt4JPBljCoTTjXSsXbPEQ6thDJ0p
"""

import pandas as pd
df = pd.read_csv("emails.csv")

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle
import re
from datetime import datetime
import os

st.set_page_config(
    page_title="Phishing Email Detector",
    page_icon="🛡️",
    layout="wide"
)

# Custom CSS
st.markdown("""
    <style>
    .phishing-alert {
        padding: 20px;
        background-color: #ff4444;
        color: white;
        border-radius: 10px;
        margin: 10px 0;
        animation: pulse 2s infinite;
    }
    .safe-alert {
        padding: 20px;
        background-color: #44ff44;
        color: #006600;
        border-radius: 10px;
        margin: 10px 0;
    }
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.7; }
    }
    </style>
""", unsafe_allow_html=True)

# Initialize session state
if 'model' not in st.session_state:
    st.session_state.model = None
if 'vectorizer' not in st.session_state:
    st.session_state.vectorizer = None
if 'blocked_emails' not in st.session_state:
    st.session_state.blocked_emails = []
if 'detection_history' not in st.session_state:
    st.session_state.detection_history = []

# Feature extraction functions
def extract_features(text):
    """Extract additional features from email text"""
    features = {}

    # URL count
    features['url_count'] = len(re.findall(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', text))

    # Suspicious words
    suspicious_words = ['urgent', 'verify', 'account', 'suspended', 'click', 'winner', 'prize', 'congratulations', 'password', 'update']
    features['suspicious_word_count'] = sum(1 for word in suspicious_words if word.lower() in text.lower())

    # Special characters
    features['special_char_count'] = len(re.findall(r'[!@#$%^&*()]', text))

    # Email length
    features['length'] = len(text)

    return features

def preprocess_text(text):
    """Clean and preprocess email text"""
    if pd.isna(text):
        return ""
    # Convert to lowercase
    text = str(text).lower()

    # Remove extra whitespace
    text = ' '.join(text.split())

    return text

# This cell is no longer needed as its content has been moved to cell JOniiJH8zKmj

# Training function
def train_model(df):
    """Train the phishing detection model"""

    st.info("🔄 Preprocessing data...")

    # Preprocess text
    df['processed_text'] = df['text'].apply(preprocess_text)

    # Split data
    X = df['processed_text']
    y = df['label']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    st.info("🔄 Vectorizing text...")

    # TF-IDF Vectorization
    vectorizer = TfidfVectorizer(max_features=3000, ngram_range=(1, 2), stop_words='english')
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    st.info("🔄 Training model...")

    # Train Random Forest
    model = RandomForestClassifier(n_estimators=200, max_depth=20, random_state=42, n_jobs=-1)
    model.fit(X_train_vec, y_train)

    # Evaluate
    y_pred = model.predict(X_test_vec)
    accuracy = accuracy_score(y_test, y_pred)

    return model, vectorizer, accuracy, y_test, y_pred

# Prediction function
def predict_email(email_text, model, vectorizer):
    """Predict if email is phishing or safe"""

    processed = preprocess_text(email_text)
    vectorized = vectorizer.transform([processed])
    prediction = model.predict(vectorized)[0]
    probability = model.predict_proba(vectorized)[0]

    return prediction, probability

# Main app
def main():
    st.title("🛡️ Phishing Email Detection System")
    st.markdown("### Automated Email Security Monitor")

    # Sidebar
    with st.sidebar:
        st.header("⚙️ System Controls")

        page = st.radio("Navigation", ["🏠 Home", "🎓 Train Model", "🔍 Detect Email", "📊 Analytics", "🚫 Blocked List"])

        st.markdown("---")
        st.markdown("### 📈 System Status")

        if st.session_state.model is not None:
            st.success("✅ Model Loaded")
        else:
            st.warning("⚠️ Model Not Trained")

        st.metric("Blocked Emails", len(st.session_state.blocked_emails))
        st.metric("Total Scans", len(st.session_state.detection_history))

    # Home Page
    if page == "🏠 Home":
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Model Status", "✅ Ready" if st.session_state.model else "⚠️ Not Ready")
        with col2:
            st.metric("Blocked Emails", len(st.session_state.blocked_emails))
        with col3:
            st.metric("Detection Accuracy", "95%+" if st.session_state.model else "N/A")

        st.markdown("---")
        st.markdown("""
        ### 🚀 Getting Started

        1. **Train Model**: Upload your `email.csv` file to train the detection model
        2. **Detect Email**: Paste or type email content to check if it's phishing
        3. **Analytics**: View detection statistics and model performance
        4. **Blocked List**: Manage blocked emails

        ### 🔒 Features
        - ✅ Real-time phishing detection
        - ✅ Automatic alert system
        - ✅ Manual blocking with confirmation
        - ✅ Detection history tracking
        - ✅ High accuracy ML model
        """)

    # Train Model Page
    elif page == "🎓 Train Model":
        st.header("🎓 Train Detection Model")

        uploaded_file = st.file_uploader("Upload email.csv file", type=['csv'])

        if uploaded_file is not None:
            df = pd.read_csv(uploaded_file)

            st.success(f"✅ File uploaded! Found {len(df)} emails")

            # Show data preview
            with st.expander("📋 View Data Preview"):
                st.dataframe(df.head(10))
                st.write(f"**Columns:** {', '.join(df.columns)}")

            # Verify required columns
            if 'text' not in df.columns or 'label' not in df.columns:
                st.error("❌ CSV must have 'text' and 'label' columns!")
                st.info("Expected format: 'text' (email content), 'label' (0=safe, 1=phishing)")
            else:
                st.info(f"📊 Safe emails: {sum(df['label']==0)} | Phishing emails: {sum(df['label']==1)}")

                if st.button("🚀 Start Training", type="primary"):
                    with st.spinner("Training in progress..."):
                        try:
                            model, vectorizer, accuracy, y_test, y_pred = train_model(df)

                            st.session_state.model = model
                            st.session_state.vectorizer = vectorizer

                            st.success(f"🎉 Model trained successfully!")
                            st.metric("Model Accuracy", f"{accuracy*100:.2f}%")

                            # Show confusion matrix
                            with st.expander("📊 View Detailed Metrics"):
                                cm = confusion_matrix(y_test, y_pred)
                                col1, col2 = st.columns(2)

                                with col1:
                                    st.write("**Confusion Matrix:**")
                                    st.write(pd.DataFrame(cm,
                                                         columns=['Predicted Safe', 'Predicted Phishing'],
                                                         index=['Actual Safe', 'Actual Phishing']))

                                with col2:
                                    st.write("**Classification Report:**")
                                    report = classification_report(y_test, y_pred, output_dict=True)
                                    st.json(report)

                            # Save model
                            with open('phishing_model.pkl', 'wb') as f:
                                pickle.dump(model, f)
                            with open('vectorizer.pkl', 'wb') as f:
                                pickle.dump(vectorizer, f)

                            st.info("💾 Model saved to disk!")

                        except Exception as e:
                            st.error(f"❌ Error during training: {str(e)}")

    # Detect Email Page
    elif page == "🔍 Detect Email":
        st.header("🔍 Email Phishing Detection")

        if st.session_state.model is None:
            st.warning("⚠️ Please train the model first!")
        else:
            # Input methods
            input_method = st.radio("Input Method", ["📝 Type/Paste", "📁 Upload File"])

            email_text = ""

            if input_method == "📝 Type/Paste":
                email_text = st.text_area("Enter email content:", height=250,
                                         placeholder="Paste the email content here...")
            else:
                uploaded = st.file_uploader("Upload email text file", type=['txt', 'eml'])
                if uploaded:
                    email_text = uploaded.read().decode('utf-8')
                    st.text_area("Email Content:", email_text, height=200)

            if st.button("🔍 Analyze Email", type="primary") and email_text:
                with st.spinner("Analyzing email..."):
                    prediction, probability = predict_email(email_text,
                                                           st.session_state.model,
                                                           st.session_state.vectorizer)

                    # Store in history
                    st.session_state.detection_history.append({
                        'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        'prediction': prediction,
                        'confidence': max(probability) * 100,
                        'snippet': email_text[:100] + "..."
                    })

                    st.markdown("---")

                    if prediction == 1:  # Phishing
                        st.markdown(f"""
                        <div class="phishing-alert">
                            <h2>🚨 PHISHING DETECTED! 🚨</h2>
                            <p><strong>Confidence:</strong> {probability[1]*100:.2f}%</p>
                            <p>This email has been identified as a potential phishing attempt!</p>
                        </div>
                        """, unsafe_allow_html=True)

                        st.warning("⚠️ **Warning Signs Detected:**")
                        features = extract_features(email_text)

                        if features['url_count'] > 2:
                            st.write(f"- Multiple URLs found ({features['url_count']})")
                        if features['suspicious_word_count'] > 0:
                            st.write(f"- Suspicious keywords detected ({features['suspicious_word_count']})")

                        # Blocking interface
                        st.markdown("---")
                        st.subheader("🚫 Block this Email?")

                        col1, col2 = st.columns(2)
                        with col1:
                            if st.button("❌ Block Email", type="primary"):
                                st.session_state.blocked_emails.append({
                                    'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                                    'snippet': email_text[:150] + "...",
                                    'confidence': probability[1]*100
                                })
                                st.success("✅ Email blocked successfully!")
                                st.balloons()

                        with col2:
                            if st.button("✓ Mark as Safe"):
                                st.info("Email marked as safe and allowed.")

                    else:  # Safe
                        st.markdown(f"""
                        <div class="safe-alert">
                            <h2>✅ EMAIL IS SAFE</h2>
                            <p><strong>Confidence:</strong> {probability[0]*100:.2f}%</p>
                            <p>No phishing indicators detected.</p>
                        </div>
                        """, unsafe_allow_html=True)

                        st.success("This email appears to be legitimate.")

    # Analytics Page
    elif page == "📊 Analytics":
        st.header("📊 Detection Analytics")

        if not st.session_state.detection_history:
            st.info("No detection history yet. Start analyzing emails!")
        else:
            df_history = pd.DataFrame(st.session_state.detection_history)

            col1, col2, col3 = st.columns(3)

            with col1:
                total = len(df_history)
                st.metric("Total Scans", total)

            with col2:
                phishing = sum(df_history['prediction'] == 1)
                st.metric("Phishing Detected", phishing,
                         delta=f"{(phishing/total*100):.1f}%" if total > 0 else "0%")

            with col3:
                avg_conf = df_history['confidence'].mean()
                st.metric("Avg Confidence", f"{avg_conf:.1f}%")

            st.markdown("---")

            # Recent detections
            st.subheader("📜 Recent Detections")

            for idx, row in df_history.tail(10).iterrows():
                status = "🚨 PHISHING" if row['prediction'] == 1 else "✅ SAFE"
                with st.expander(f"{row['timestamp']} - {status} ({row['confidence']:.1f}% confidence)"):
                    st.write(row['snippet'])

    # Blocked List Page
    elif page == "🚫 Blocked List":
        st.header("🚫 Blocked Emails")

        if not st.session_state.blocked_emails:
            st.info("No blocked emails yet.")
        else:
            st.write(f"**Total Blocked:** {len(st.session_state.blocked_emails)}")

            for idx, email in enumerate(reversed(st.session_state.blocked_emails)):
                with st.expander(f"Blocked on {email['timestamp']} ({email['confidence']:.1f}% confidence)"):
                    st.write(email['snippet'])

                    if st.button(f"Unblock", key=f"unblock_{idx}"):
                        st.session_state.blocked_emails.pop(-(idx+1))
                        st.rerun()

            if st.button("🗑️ Clear All Blocked"):
                st.session_state.blocked_emails = []
                st.rerun()

if __name__ == "__main__":
    main()

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit pandas scikit-learn numpy

# To run the Streamlit app, save the Python code as a .py file and run it from your terminal
# using the command `streamlit run your_script_name.py`.
# If you want to run it directly in Colab, you can use the following command:
# !streamlit run your_script_name.py & npx localtunnel --port 8501
# Replace 'your_script_name.py' with the actual name of your Python file.

# For demonstration purposes within Colab, you can call the main function directly if the app structure allows
# (Note: This will not run the full Streamlit server in the same way as `streamlit run`)
main()